services:
  - type: cron
    name: collect-data-job
    runtime: python
    repo: https://github.com/vAngelowBG/vatips
    plan: free
    schedule: "0 3 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python collect_data.py

  - type: cron
    name: train-model-job
    runtime: python
    repo: https://github.com/vAngelowBG/vatips
    plan: free
    schedule: "30 3 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python train_model.py

  - type: cron
    name: predict-job
    runtime: python
    repo: https://github.com/vAngelowBG/vatips
    plan: free
    schedule: "0 4 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python predict.py
